### PR TITLE
Add TravisCI and build fixes

### PR DESCRIPTION
**Pull request by am11**
* add `.travis.yml`
  * build example: https://travis-ci.org/am11/Homoglyph/builds/582616030
* add `fastutil` dependency in `pom.xml`
* add `testSourceDirectory` and make the test files end with `*Test.java` (the pattern which `mvn-install` recognizes OOTB) instead of `*Tests.java`

### CODE REVIEW

**Comment by am11** [comment]
@egg82, i was trying to figure out this behavior:

```java
// this holds true
Assertions.assertEquals("test", helper.toASCII("test"));
// this one fails
Assertions.assertEquals("text", helper.toASCII("text"));
// this one also holds true
Assertions.assertTrue(helper.equals("text","text"));
```

the failing assertion reports:

```
Failed tests:   ninja.egg82.homoglyph.StandardTest.testASCII(): expected: <text> but was: <te×t>
```

`×` -> 215
vs.
`x` -> 120

could you please tell if it is a bug or an expected behavior?

**Comment by egg82** [comment]
Travis looks good! I'll also take a look at the odd (Unicode?) issue

**Comment by am11** [comment]
I have opened an issue for that oddity: https://github.com/egg82/Homoglyph/issues/2. (-8

**Comment by egg82** [comment]
Closed in favor of Jenkins

**Pull request closed without merging**
